// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsflovMFBOYAI4dIKk7SWhKprlkN_ArNY',
    appId: '1:518456025074:web:d68350e7112da44ee6956b',
    messagingSenderId: '518456025074',
    projectId: 'aplikasi-smart-green-house',
    authDomain: 'aplikasi-smart-green-house.firebaseapp.com',
    databaseURL: 'https://aplikasi-smart-green-house-default-rtdb.firebaseio.com',
    storageBucket: 'aplikasi-smart-green-house.appspot.com',
    measurementId: 'G-SRMERMQBY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm7bGA-6VT41H3b_kMhFe-womEJfRTMgU',
    appId: '1:518456025074:android:c33fec0f36b490c8e6956b',
    messagingSenderId: '518456025074',
    projectId: 'aplikasi-smart-green-house',
    databaseURL: 'https://aplikasi-smart-green-house-default-rtdb.firebaseio.com',
    storageBucket: 'aplikasi-smart-green-house.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTFZARoAWtfEbBFI46UUSnuHMwkFtSNNA',
    appId: '1:518456025074:ios:132bd96aee188994e6956b',
    messagingSenderId: '518456025074',
    projectId: 'aplikasi-smart-green-house',
    databaseURL: 'https://aplikasi-smart-green-house-default-rtdb.firebaseio.com',
    storageBucket: 'aplikasi-smart-green-house.appspot.com',
    iosBundleId: 'com.example.aplikasiSmartGreenHouse',
  );
}
